facts = [
    "There is a hacker attack every 39 seconds.",
    "Russian hackers are the fastest.",
    "300,000 new malware is created every day.",
    "Multi-factor authentication and encryption are the biggest hacker obstacles."
    "You can become an American citizen for $6,000.",
    "The average cost of data breaches will be about 150 million in 2020.",
    "The cybersecurity budget in the US is $14.98 billion.",
    "Cybercrime is more profitable than the global illegal drug trade.",
    "Hackers steal 75 records every second.",
    "66% of businesses attacked by hackers weren’t confident they could recover.",
    "73% of black hat hackers said traditional firewall and antivirus security is irrelevant or obsolete.",
    "The cybersecurity budget in the US was $14.98 billion in 2019.",
    "White hat hackers earned over $19 million in bounties in 2018.",
    "There are over 715,000 cybersecurity experts employed in the US alone.",
    "Russian hackers can infiltrate a computer network in 18 minutes.",
    "Hackers are the average American’s biggest fear.",
    "You can purchase a consumer account for $1 on the dark market.",
    "More than 6,000 online criminal marketplaces sell ransomware products and services.",
    "444,259 ransomware attacks took place worldwide in 2018.",
    "Hackers create 300,000 new pieces of malware daily.",
    "There will be 3.5 million cybersecurity jobs openings in 2021.",
    "32% of black hat hackers admit privileged accounts are their number one way to hack systems.",
    "75% of all attacked businesses reported fraudulent emails.",
    "Companies protect only 3% of their folders.",
    "Up until March 2019, more than 14 billion data records had been lost or stolen.",
    "Yahoo’s data breach – 3 billion compromised accounts.",
    "209,000 payment card numbers and expiration dates were stolen from Equifax.",
    "Marriot International – 500 million users’ data stolen.",
    "The cost of data breaches will increase to $150 million in 2020.",
    "Hackers siphoned off $13.4 million from Cosmos Bank in India.",
    "The Carbanak gang of hackers has stolen over $1 billion in total.",
    "Cybercrime cost the world almost $600 billion in 2018.",
    "For as low as $1.25 you can get a Netflix account.",
    "You can purchase the WinPot malware for 1 bitcoin.",
    "92% of ATMs are vulnerable to hacker attacks.",
    "The Tor network had more than 2.2 million users in 2017.",
]